# Užduotys
**Atkreipkite dėmesį, kad, jeigu neteisingai įvsite atsakymą, Out reikšmė irgi pasikeis**

In [2]:
import numpy as np

1\. Sukurkite vektorių su skaičiais nuo 1 iki 9

In [3]:

vektorius = np.arange(1, 10)
vektorius

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

2\. Sukurkite vektorių iš 10 nulių

In [4]:

vektorius1 = np.zeros(10)
vektorius1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3\. Sukurkite vektorių iš 10 vienetų

In [4]:
vektorius2 = np.ones(10)
vektorius2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4\. Sukurkite vektorių iš 10 ketvertų

In [ ]:
vektorius3 =np.ones(10) * 4
vektorius3

5\. Sukurkite vektorių iš lyginių skaičių nuo 0 iki 100

In [11]:
vektorius4 = np.arange(0, 102, 2)
vektorius4

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

6\. Sukurkite matricą iš 25 narių, pradedant 1, baigiant 25. Priskirkite ją kintamąjam.

In [14]:
matrica = np.matrix(np.arange(1, 26)).reshape(5, 5)
matrica

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])

7\. Iš matricos ištraukite skaičių 12

In [18]:
dvylika = matrica.item(2, 1)
dvylika


12

In [17]:
matrica[2, 1]

12

8\. Iš matricos ištraukite paskutinę eilutę.

In [20]:
matrica[-1, :]

matrix([[21, 22, 23, 24, 25]])

9\. Iš matricos ištraukite submatricą

1, 2, 3  
6, 7, 8  
11,12,13

In [28]:
matrica[:3, :3]

matrix([[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 12, 13]])

10\. Iš matricos ištraukite submatricą

7, 8, 9, 10  
12, 13, 14, 15  
17, 18, 19, 20

In [24]:
submatrix = matrica[1:, 1:]
print(submatrix)

[[ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


11\. Iš matricos ištraukite submatricą

16, 17, 18  
21, 22, 23

In [30]:
matrica[3:, :3]

matrix([[16, 17, 18],
        [21, 22, 23]])

12\. Sukurkite vektorių iš 20 atsitiktinių reikšmių nuo 0 iki 1. Priskirkite kintamąjam.

In [33]:
atsitiktinis = np.random.random(20)
atsitiktinis

array([0.17325552, 0.5136409 , 0.54378347, 0.74351395, 0.99851341,
       0.62588177, 0.55509384, 0.24165592, 0.08574132, 0.05905998,
       0.32633212, 0.32269929, 0.79235799, 0.34727004, 0.89315544,
       0.66734719, 0.52303924, 0.94878926, 0.50652141, 0.2613573 ])

13\. Suraskite didžiausią reikšmę masyve ir jos indeksą.

In [38]:
print(atsitiktinis.max())
atsitiktinis.argmax()


0.9985134090577283


4

14\. Suraskite mažiausią reikšmę ir jos indeksą

In [39]:
print(atsitiktinis.min())
atsitiktinis.argmin()

0.05905998258996259


9

15\. Atspausdinkite šios matricos duomenų tipą

In [42]:
atsitiktinis.dtype

dtype('float64')

16\. Sukurkite vektorių iš integer reikšmių nuo 1 iki 100. Priskirkite kintamąjam. Iš jo ištraukite visus skaičius, didesnius už 90

In [47]:
didelis = np.arange(1, 101)
didelis


array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [48]:
didelis[didelis>90]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

17\. Ištraukite iš vektoriaus visus skaičiaus 7 kartotinius

In [49]:
didelis[didelis %7==0]

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

18\. Sukurkite tokią matricą:

In [55]:
# array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
#        [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
#        [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
#        [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
#        [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])


In [57]:
tarpine = np.linspace(0, 1, 41)

In [58]:
tarpine

array([0.   , 0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ,
       0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  , 0.425,
       0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  , 0.625, 0.65 ,
       0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  , 0.825, 0.85 , 0.875,
       0.9  , 0.925, 0.95 , 0.975, 1.   ])

19\. sukurkite tokią matricą (sveiki sk. nuo 2 iki 1000 iš kurių traukiasi sveika šaknis):

In [74]:
# array([[  4,   9,  16,  25,  36],
#        [ 49,  64,  81, 100, 121],
#        [144, 169, 196, 225, 256],
#        [289, 324, 361, 400, 441],
#        [484, 529, 576, 625, 676],
#        [729, 784, 841, 900, 961]])

In [69]:
didele_matrica = np.arange(2, 1000)


In [74]:
nauja_matrica = didele_matrica[(didele_matrica ** 0.5) % 1 ==0].reshape(6,5)
nauja_matrica

array([[  4,   9,  16,  25,  36],
       [ 49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256],
       [289, 324, 361, 400, 441],
       [484, 529, 576, 625, 676],
       [729, 784, 841, 900, 961]])

20\. **(BONUS)**
* Sukurkite vektorių iš sveikų sk. nuo 1 iki 100. Priskirkite kintamąjam.
* Sukurkite Python funkciją, kuri tikrina ar parametruose įvestas sk. yra pirminis. Jeigu pirminis, grąžina True, jei ne, False.
* NumPy nevisada supranta įprastą Python kodą su range'ais ir list'ais, todėl sukurtą funkciją teks vektorizuoti taip : **nauja_funkcija = np.vectorize(jūsų_funkcija)**  .
* Kadangi sąlygos reikšmių traukimui yra *bool* reikšmės, pabandykite vietoje sąlygos įdėti savo vektorizuotą funkciją, ir taip išrinkti pirminius skaičius iš savo vektoriaus
.

In [138]:
kintamasis = np.arange(1, 101)
kintamasis

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [139]:
def tikrinam(skaicius):
    for x in range(2, skaicius):
        if skaicius%x==0:
            return False

    return True

    

In [133]:
def tikrinam_dar(nampai):
    for skaicius in nampai:
        i = 0
        for x in range(1, skaicius):
            if skaicius%x == 0:
                i += 1
        if i==1:
            return True
        return False

In [142]:
nauja_funkcija = np.vectorize(tikrinam)
funkcija = np.vectorize(tikrinam_dar)

print(nauja_funkcija(kintamasis))

TypeError: 'numpy.int32' object is not iterable

In [143]:
# kintamasis[nauja_funkcija(kintamasis)]
kintamasis[nauja_funkcija(kintamasis)]

array([ 1,  2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53,
       59, 61, 67, 71, 73, 79, 83, 89, 97])