In [2]:
import numpy as np

In [3]:
sarasas = [5, 1, 7, 6]
vektorius = np.array(sarasas)
print(vektorius)

[5 1 7 6]


In [4]:
sarasai = [
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9]
]
matrica = np.matrix(sarasai)
matrica

matrix([[4, 5, 6],
        [1, 2, 3],
        [7, 8, 9]])

In [5]:
print(np.arange(0, 89, 8))
np.arange(0, 89, 8)

[ 0  8 16 24 32 40 48 56 64 72 80 88]


array([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88])

In [6]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [7]:
print(np.zeros(7))

[0. 0. 0. 0. 0. 0. 0.]


In [8]:
print(np.zeros((7, 7), dtype=int))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [9]:
print(np.linspace(0, 20, 9))

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20. ]


In [10]:
vienetine = np.eye(5, k=-1)

vienetine[3,4] = 5
print(vienetine)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 5.]
 [0. 0. 0. 1. 0.]]


# random array/matricos

In [11]:
np.random.rand(10)

array([0.74911938, 0.33584858, 0.85708905, 0.41985599, 0.40926948,
       0.80778506, 0.45203113, 0.06367466, 0.90205929, 0.55074277])

In [12]:

print(np.random.randn(3, 3))

[[-0.4294505   0.3196425  -0.22630345]
 [ 0.95341966  0.55482589 -0.18479244]
 [-1.56036118  1.77211598 -0.75000232]]


In [13]:
np.random.rand(3, 3)

array([[0.92158167, 0.52224444, 0.68950112],
       [0.83472873, 0.07953653, 0.34401352],
       [0.85001179, 0.82356405, 0.74044229]])

In [14]:
bandom = np.random.randint(-10, 11, 77)
print(bandom)
print(type(bandom))

[ 10  10   5  -2   5  -6   6  -4  -5  -8   2  -4 -10   5  -3   4  -9  -1
   5   5  -2 -10   8   0   8  -9   4  -5   8  -1   7  10  -9   5  -2   1
  -6  -9   5   0  -2  -8  -8   7  10   5  -1   3   6  -6   0  -2  -9   0
   0  -6  -9   4   0  -6   0   9  -5   3   8  -5  -5   7  -8   1   5   3
  -1  -5  -8  -8   9]
<class 'numpy.ndarray'>


# masyvu pertvarkymas

In [15]:
masyvas = np.random.randint(-9, 10, 40)
pertvarkytas = masyvas.reshape(5, 8)
print(pertvarkytas)


[[-5  9 -2 -1 -4  3  1 -5]
 [-5 -9  9  3  0  1 -8 -1]
 [ 5 -4  4  9 -5  1 -9  0]
 [-3  1  8  1 -9  9  2 -3]
 [-6 -9 -4  8  0  5  2  4]]


In [16]:
print(pertvarkytas.min())
print(pertvarkytas.max())

-9
9


In [17]:
print(pertvarkytas.argmin())
print(pertvarkytas.argmax())
print(pertvarkytas.shape)

9
1
(5, 8)


# masyvu pertvarkymas

In [18]:
masyvas = np.random.randint(-9, 10, 40)

masyvas.reshape(5, 8)


array([[ 3, -5,  9,  4, -8, -2,  0,  7],
       [ 7, -9,  4, -7,  9,  9,  9, -7],
       [ 1,  2,  0,  6,  3,  0, -7, -6],
       [ 7,  8, -3, -5, -4, -7, -4,  0],
       [ 1, -9, -6,  7, -6, -4,  1, -1]])

In [19]:
masyvas[5]

-2

In [20]:
masyvas[3:13]

array([ 4, -8, -2,  0,  7,  7, -9,  4, -7,  9])

In [21]:
masyvas[::4] = 44
masyvas[7]

7

In [22]:
pertvarkytas[0,0]


-5

In [23]:
pertvarkytas[1:4, 5:8]

array([[ 1, -8, -1],
       [ 1, -9,  0],
       [ 9,  2, -3]])

In [24]:
bandom = np.random.randint(0, 101, 100)
matrica = bandom.reshape(10, 10)
matrica

array([[76, 43,  4, 10, 89, 99, 74, 37, 94, 22],
       [28, 74, 77, 90, 31, 98, 17, 64, 58,  2],
       [85, 52, 79, 52,  8, 95, 88, 44, 85, 69],
       [54, 32,  8,  3, 25, 92, 45, 22, 72, 80],
       [99, 80, 34, 97, 34, 30, 75, 38, 27, 84],
       [66, 99, 87, 95, 90, 45, 96, 26, 46, 77],
       [33, 81, 86, 44, 79, 45, 78, 90,  7, 83],
       [49, 34, 81, 33,  7, 99, 78, 62, 49, 26],
       [97, 24, 93, 18, 38, 50, 81, 40, 74,  2],
       [83, 23, 52,  2, 71, 10, 56, 83, 93, 58]])

In [25]:
matrica[::2, ::2]

array([[76,  4, 89, 74, 94],
       [85, 79,  8, 88, 85],
       [99, 34, 34, 75, 27],
       [33, 86, 79, 78,  7],
       [97, 93, 38, 81, 74]])

In [26]:
matrica[-2::-2, -2::-2]

array([[74, 81, 38, 93, 97],
       [ 7, 78, 79, 86, 33],
       [27, 75, 34, 34, 99],
       [85, 88,  8, 79, 85],
       [94, 74, 89,  4, 76]])

In [27]:
matrica[:, :1]

array([[76],
       [28],
       [85],
       [54],
       [99],
       [66],
       [33],
       [49],
       [97],
       [83]])

In [28]:
matrica[3:5, :]

array([[54, 32,  8,  3, 25, 92, 45, 22, 72, 80],
       [99, 80, 34, 97, 34, 30, 75, 38, 27, 84]])

# traukimas pagal salyga

In [29]:
masyvas

array([44, -5,  9,  4, 44, -2,  0,  7, 44, -9,  4, -7, 44,  9,  9, -7, 44,
        2,  0,  6, 44,  0, -7, -6, 44,  8, -3, -5, 44, -7, -4,  0, 44, -9,
       -6,  7, 44, -4,  1, -1])

In [30]:
masyvas > 3

array([ True, False,  True,  True,  True, False, False,  True,  True,
       False,  True, False,  True,  True,  True, False,  True, False,
       False,  True,  True, False, False, False,  True,  True, False,
       False,  True, False, False, False,  True, False, False,  True,
        True, False, False, False])

In [31]:
masyvas[masyvas > 3]

array([44,  9,  4, 44,  7, 44,  4, 44,  9,  9, 44,  6, 44, 44,  8, 44, 44,
        7, 44])

In [32]:
iki_3 = masyvas < 3
print(iki_3)

[False  True False False False  True  True False False  True False  True
 False False False  True False  True  True False False  True  True  True
 False False  True  True False  True  True  True False  True  True False
 False  True  True  True]


In [33]:
masyvas[iki_3]

array([-5, -2,  0, -9, -7, -7,  2,  0,  0, -7, -6, -3, -5, -7, -4,  0, -9,
       -6, -4,  1, -1])

In [34]:
masyvas[iki_3] = 3
masyvas

array([44,  3,  9,  4, 44,  3,  3,  7, 44,  3,  4,  3, 44,  9,  9,  3, 44,
        3,  3,  6, 44,  3,  3,  3, 44,  8,  3,  3, 44,  3,  3,  3, 44,  3,
        3,  7, 44,  3,  3,  3])

In [35]:
np.array([x for x in masyvas if x > 3])

array([44,  9,  4, 44,  7, 44,  4, 44,  9,  9, 44,  6, 44, 44,  8, 44, 44,
        7, 44])

In [36]:
naujas = np.random.randint(0, 99, 20)
print(naujas)
naujas[naujas > 50] = [50+x for x in naujas if x >50]
naujas

[53 40 41  4 64 47 14 61 89 37 56 36 25 26 66 22 42 45 22 92]


array([103,  40,  41,   4, 114,  47,  14, 111, 139,  37, 106,  36,  25,
        26, 116,  22,  42,  45,  22, 142])

In [37]:
masyvas_naujas = np.random.randint(0, 90, 100)
kopija = masyvas_naujas.copy()[30:60]



print(masyvas_naujas)
print(kopija)


[89 56 52 84 41 23 38 40  8 32 70 75 11 76 55 41 80 15  8 45 15  5 15 70
 25 13 45 37 28 55 86  1 56 47 67 47 66 85 86 75 58 62 32 80 63 38 64 60
  9 87 72 55 86  7 72 66 55 89 87 70 37 57 25 24 16 38 31 86 59 81 69 75
 58 61 56 42 33 50 84 13 31 44 75 44 10 78 26 40 30 35 47 77 39 36 49 72
 63 72 16 30]
[86  1 56 47 67 47 66 85 86 75 58 62 32 80 63 38 64 60  9 87 72 55 86  7
 72 66 55 89 87 70]


In [38]:
kombinuotas = [x for x in masyvas_naujas if x>30 and x<60]
print(kombinuotas)

[56, 52, 41, 38, 40, 32, 55, 41, 45, 45, 37, 55, 56, 47, 47, 58, 32, 38, 55, 55, 37, 57, 38, 31, 59, 58, 56, 42, 33, 50, 31, 44, 44, 40, 35, 47, 39, 36, 49]


In [39]:
tarpinis = masyvas_naujas[masyvas_naujas >= 30]
tarpinis[tarpinis <60]

array([56, 52, 41, 38, 40, 32, 55, 41, 45, 45, 37, 55, 56, 47, 47, 58, 32,
       38, 55, 55, 37, 57, 38, 31, 59, 58, 56, 42, 33, 50, 31, 44, 44, 40,
       30, 35, 47, 39, 36, 49, 30])

In [40]:
vektorius = np.arange(1, 11, 1)
vektorius

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
vektorius ** 3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [42]:
vektorius ** 3 / vektorius

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [43]:
(vektorius + 100) / 10

array([10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ])

In [44]:
np.cos(vektorius)
np.log(vektorius ** 2)
np.tan(vektorius)
np.sin(vektorius)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [46]:
bandomoji = np.full((5,5), 9)
bandomoji

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])