In [2]:
import numpy as np

In [10]:
sarasas = [5, 1, 7, 6]
vektorius = np.array(sarasas)
print(vektorius)

[5 1 7 6]


In [5]:
sarasai = [
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9]
]
matrica = np.matrix(sarasai)
matrica

matrix([[4, 5, 6],
        [1, 2, 3],
        [7, 8, 9]])

In [9]:
print(np.arange(0, 89, 8))
np.arange(0, 89, 8)

[ 0  8 16 24 32 40 48 56 64 72 80 88]


array([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88])

In [14]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [13]:
print(np.zeros(7))

[0. 0. 0. 0. 0. 0. 0.]


In [ ]:
print(np.zeros((7, 7), dtype=int))

In [20]:
print(np.linspace(0, 20, 9))

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20. ]


In [36]:
vienetine = np.eye(5, k=-1)

vienetine[3,4] = 5
print(vienetine)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 5.]
 [0. 0. 0. 1. 0.]]


# random array/matricos

In [32]:
np.random.rand(10)

array([0.05186286, 0.51719953, 0.22873735, 0.30541963, 0.77503778,
       0.6243701 , 0.73754053, 0.37477656, 0.91427387, 0.57690918])

In [39]:

print(np.random.randn(3, 3))

[[ 0.70907238 -0.69590251  0.9387054 ]
 [-0.19602833  1.48346725 -1.00235619]
 [ 0.04665091  0.58360111 -0.96252752]]


In [35]:
np.random.rand(3, 3)

array([[0.70899391, 0.45206772, 0.50815754],
       [0.09935268, 0.60807049, 0.74773417],
       [0.61286866, 0.67401757, 0.86078835]])

In [45]:
bandom = np.random.randint(-10, 11, 77)
print(bandom)
print(type(bandom))

[  2   2  -6  -2  -6  -1   1   2  10  -8   0   2   3   8   3   2  -8  -5
  -8  -2   9   0   4   9  -5  -3   6   6   8   5   5  -9   5   4  -3   0
  -5  -1 -10   4   8  -5   9  -6  -5   6  -6  -6   2  -7 -10  -6   4  -9
  -5  -4  -4   4  -8  -9   1   5  10   5   3   0  -9  -2   4 -10  -1  -8
   6  -7  -2   2  -3]
<class 'numpy.ndarray'>


# masyvu pertvarkymas

In [80]:
masyvas = np.random.randint(-9, 10, 40)
pertvarkytas = masyvas.reshape(5, 8)
print(pertvarkytas)


[[ 7  6  4 -6  3  9 -3 -3]
 [ 3 -6 -3  1 -5 -3  0  5]
 [-6  9 -1 -4  9 -3  3  1]
 [-3 -5 -8 -2  7  3 -1  1]
 [ 3  6  4  7  8  6 -1  8]]


In [82]:
print(pertvarkytas.min())
print(pertvarkytas.max())

-8
9


In [81]:
print(pertvarkytas.argmin())
print(pertvarkytas.argmax())
print(pertvarkytas.shape)

26
5
(5, 8)


# masyvu pertvarkymas

In [75]:
masyvas = np.random.randint(-9, 10, 40)

masyvas.reshape(5, 8)


array([[ 0, -8, -8, -4,  9, -1,  3,  6],
       [ 6,  7,  5,  4,  0,  2, -2,  9],
       [-1,  6,  3, -9,  8,  7,  7,  8],
       [-8,  5,  9,  6, -1, -7,  7,  3],
       [ 7,  1, -7,  6, -4, -8,  1, -2]])

In [76]:
masyvas[5]

-1

In [77]:
masyvas[3:13]

array([-4,  9, -1,  3,  6,  6,  7,  5,  4,  0])

In [78]:
masyvas[::4] = 44
masyvas[7]

In [73]:
pertvarkytas[0,0]


44

In [83]:
pertvarkytas[1:4, 5:8]

array([[-3,  0,  5],
       [-3,  3,  1],
       [ 3, -1,  1]])

In [84]:
bandom = np.random.randint(0, 101, 100)
matrica = bandom.reshape(10, 10)
matrica

array([[ 95,  25,  34,  51,  12,   8,   8,  94,  81,   4],
       [ 64,  40,  20,  76,  50,  73,  38,  66, 100,  26],
       [ 42,  77,  78,  11,  80,  28,  90,   7,  63,  67],
       [ 21,  51,  14,  70,  58,  24,  88,  40,  84,  10],
       [ 54,   2,  24,  58,  85,  61,  88,   0,  40,  17],
       [ 46,  96,  33,  77,  15,  97,   9,   8,  90,  63],
       [ 43,  77,  36,   3,  48,  56,  64,  39,  55,  13],
       [ 73,  64,  37,  61,  47,  11,  83,  20,  14,   6],
       [ 38,   9,  69,  55,  54,  70,  58,   1,  74,  53],
       [ 32,  20,  84,  59,  22,  54,  11,  83,  29,  94]])

In [85]:
matrica[::2, ::2]

array([[95, 34, 12,  8, 81],
       [42, 78, 80, 90, 63],
       [54, 24, 85, 88, 40],
       [43, 36, 48, 64, 55],
       [38, 69, 54, 58, 74]])

In [86]:
matrica[-2::-2, -2::-2]

array([[74, 58, 54, 69, 38],
       [55, 64, 48, 36, 43],
       [40, 88, 85, 24, 54],
       [63, 90, 80, 78, 42],
       [81,  8, 12, 34, 95]])

In [87]:
matrica[:, :1]

array([[95],
       [64],
       [42],
       [21],
       [54],
       [46],
       [43],
       [73],
       [38],
       [32]])

In [92]:
matrica[3:5, :]

array([[21, 51, 14, 70, 58, 24, 88, 40, 84, 10],
       [54,  2, 24, 58, 85, 61, 88,  0, 40, 17]])

# traukimas pagal salyga

In [112]:
masyvas

array([7, 6, 4, 3, 3, 9, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 3, 9, 3, 3, 9, 3,
       3, 3, 3, 3, 3, 3, 7, 3, 3, 3, 3, 6, 4, 7, 8, 6, 3, 8])

In [97]:
masyvas > 3

array([ True,  True,  True, False, False,  True, False, False, False,
       False, False, False, False, False, False,  True, False,  True,
       False, False,  True, False, False, False, False, False, False,
       False,  True, False, False, False, False,  True,  True,  True,
        True,  True, False,  True])

In [95]:
masyvas[masyvas > 3]

array([7, 6, 4, 9, 5, 9, 9, 7, 6, 4, 7, 8, 6, 8])

In [98]:
iki_3 = masyvas < 3
print(iki_3)

[False False False  True False False  True  True False  True  True  True
  True  True  True False  True False  True  True False  True False  True
  True  True  True  True False False  True  True False False False False
 False False  True False]


In [99]:
masyvas[iki_3]

array([-6, -3, -3, -6, -3,  1, -5, -3,  0, -6, -1, -4, -3,  1, -3, -5, -8,
       -2, -1,  1, -1])

In [109]:
masyvas[iki_3] = 3
masyvas

array([7, 6, 4, 3, 3, 9, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 3, 9, 3, 3, 9, 3,
       3, 3, 3, 3, 3, 3, 7, 3, 3, 3, 3, 6, 4, 7, 8, 6, 3, 8])

In [115]:
np.array([x for x in masyvas if x > 3])

array([7, 6, 4, 9, 5, 9, 9, 7, 6, 4, 7, 8, 6, 8])

In [123]:
naujas = np.random.randint(0, 99, 20)
print(naujas)
naujas[naujas > 50] = [50+x for x in naujas if x >50]
naujas

[83 15 51 87 22  7  9 55 51 88 96 82  2 37 80 44 93 60 71 69]


array([133,  15, 101, 137,  22,   7,   9, 105, 101, 138, 146, 132,   2,
        37, 130,  44, 143, 110, 121, 119])

In [139]:
masyvas_naujas = np.random.randint(0, 90, 100)
kopija = masyvas_naujas.copy()[30:60]



print(masyvas_naujas)
print(kopija)


[27 35 70 35 12 50 16  1 86  1 87 73  5  8  8 67  8 73 61 47 66 82 35 27
 24 10 63 11 80 70  4 83 52 70 28 29 65 84 15 61 12 82 48  8 19 74 37 75
 49 51 17 67 25 59 35 33  6 72 86 68 49 19 23 86 45 26  7 22 22 48 20  2
 49 45 16 41 61 42  5 23 79  0 50 60 64 15 61  5 30 22 68 49 37 58 53 88
 84 71 46 84]
[ 4 83 52 70 28 29 65 84 15 61 12 82 48  8 19 74 37 75 49 51 17 67 25 59
 35 33  6 72 86 68]


In [144]:
kombinuotas = [x for x in masyvas_naujas if x>30 and x<60]
print(kombinuotas)

[35, 35, 50, 47, 35, 52, 48, 37, 49, 51, 59, 35, 33, 49, 45, 48, 49, 45, 41, 42, 50, 49, 37, 58, 53, 46]


In [146]:
tarpinis = masyvas_naujas[masyvas_naujas >= 30]
tarpinis[tarpinis <60]

array([35, 35, 50, 47, 35, 52, 48, 37, 49, 51, 59, 35, 33, 49, 45, 48, 49,
       45, 41, 42, 50, 30, 49, 37, 58, 53, 46])

In [147]:
vektorius = np.arange(1, 11, 1)
vektorius

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [148]:
vektorius ** 3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [149]:
vektorius ** 3 / vektorius

array([  1.,   4.,   9.,  16.,  25.,  36.,  49.,  64.,  81., 100.])

In [150]:
(vektorius + 100) / 10

array([10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9, 11. ])

In [156]:
np.cos(vektorius)
np.log(vektorius ** 2)
np.tan(vektorius)
np.sin(vektorius)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])